
type Query {
findBusinessWithCustomEndpointParameters(farmName: String): Farm
      @cypher(
        statement: """
        match(f:Farm { name: $farmName }) return f
        """,
        columnName: "f"
      )
  }

type Component @node {
	componentshasSubComponent: [Component!]! @relationship(type: "has_sub_component", direction: IN)
	containsBluePrintComponentBlueprints: [ComponentBlueprint!]! @relationship(type: "contains_blue_print", direction: OUT)
	deviceshasComponent: [Device!]! @relationship(type: "has_component", direction: IN)
	hasSubComponentComponents: [Component!]! @relationship(type: "has_sub_component", direction: OUT)
	installed_at: Date!
	label: String!
	serial_number: BigInt!
	serviced_at: Date!
}

type ComponentBlueprint @node {
	componentBlueprintshasSubComponentBlueprint: [ComponentBlueprint!]! @relationship(type: "has_sub_component_blueprint", direction: IN)
	componentscontainsBluePrint: [Component!]! @relationship(type: "contains_blue_print", direction: IN)
	devicescontainsBluePrint: [Device!]! @relationship(type: "contains_blue_print", direction: IN)
	hasSubComponentBlueprintComponentBlueprints: [ComponentBlueprint!]! @relationship(type: "has_sub_component_blueprint", direction: OUT)
	hotspotsmarksLocationOf: [Hotspot!]! @relationship(type: "marks_location_of", direction: IN)
	id: String!
	label: String!
}

type DeLavalSubscription @node {
	expiry_date: Date!
	farmsholdsSubscription: [Farm!]! @relationship(type: "holds_subscription", direction: IN)
	license_number: BigInt!
	type: String!
}

type Device @node {
	containsBluePrintComponentBlueprints: [ComponentBlueprint!]! @relationship(type: "contains_blue_print", direction: OUT)
	farmshasDevice: [Farm!]! @relationship(type: "has_device", direction: IN)
	hardware_version: Float!
	hasComponentComponents: [Component!]! @relationship(type: "has_component", direction: OUT)
	hasDeviceTypeDeviceTypes: [DeviceType!]! @relationship(type: "has_device_type", direction: OUT)
	installed_at: Date!
	label: String!
	serial_number: BigInt!
	serviced_at: Date!
}

type DeviceType @node {
	deviceshasDeviceType: [Device!]! @relationship(type: "has_device_type", direction: IN)
	name: String!
}

type Farm @node {
	hasDeviceDevices: [Device!]! @relationship(type: "has_device", direction: OUT)
	holdsSubscriptionDeLavalSubscriptions: [DeLavalSubscription!]! @relationship(type: "holds_subscription", direction: OUT)
	name: String!
	region: String!
}

type Hotspot @node {
	file: String!
	id: String!
	linkId: String!
	marksLocationInImages: [Image!]! @relationship(type: "marks_location_in", direction: OUT)
	marksLocationOfComponentBlueprints: [ComponentBlueprint!]! @relationship(type: "marks_location_of", direction: OUT)
}

type Image @node {
	hotspotsmarksLocationIn: [Hotspot!]! @relationship(type: "marks_location_in", direction: IN)
	path: String!
}
